"""
Configuration des sources de données pour l'ETL ObRail Europe.

Chaque source possède:
- max_age_hours: Âge maximum en heures avant téléchargement forcé
- enabled: Activer/désactiver la source
"""

# Sources finales retenues pour l'ETL ObRail
SOURCES = {
    "back_on_track": {
        "name": "Back-on-Track Night Train Database",
        "type": "json_api",
        "url": "https://raw.githubusercontent.com/Back-on-Track-eu/night-train-data/main/data/latest",
        "freshness_url": "https://raw.githubusercontent.com/Back-on-Track-eu/night-train-data/main/data/latest/agencies.json",
        "country": "EU",
        "licence": "GPL-3.0",
        "priority": 1,
        "max_age_hours": 720,
        "enabled": True,
        "endpoints": [
            "agencies",
            "stops",
            "routes",
            "trips",
            "trip_stop",
            "calendar",
            "calendar_dates",
            "translations",
            "classes",
        ],
    },
    "mobility_catalog": {
        "name": "Mobility Database Catalogs",
        "type": "csv",
        "url": "https://storage.googleapis.com/storage/v1/b/mdb-csv/o/sources.csv?alt=media",
        "country": "WW",
        "licence": "Apache-2.0",
        "priority": 3,
        "max_age_hours": 720,
        "enabled": True,
    },
    "sncf_intercites": {
        "name": "SNCF Intercités",
        "type": "gtfs",
        "url": "https://eu.ftp.opendatasoft.com/sncf/gtfs/export-intercites-gtfs-last.zip",
        "country": "FR",
        "licence": "ODbL",
        "priority": 1,
        "max_age_hours": 168,
        "enabled": True,
    },
    "sncf_tgv": {
        "name": "SNCF TGV",
        "type": "gtfs",
        "url": "https://eu.ftp.opendatasoft.com/sncf/gtfs/export_gtfs_voyages.zip",
        "country": "FR",
        "licence": "ODbL",
        "priority": 1,
        "max_age_hours": 168,
        "enabled": True,
    },
    "db_fernverkehr": {
        "name": "Deutsche Bahn - Fernverkehr",
        "type": "gtfs",
        "url": "https://download.gtfs.de/germany/fv_free/latest.zip",
        "country": "DE",
        "licence": "CC-BY-4.0",
        "priority": 1,
        "max_age_hours": 168,
        "enabled": True,
    },
    "renfe": {
        "name": "Renfe Espagne",
        "type": "gtfs",
        "url": "https://ssl.renfe.com/gtransit/Fichero_AV_LD/google_transit.zip",
        "country": "ES",
        "licence": "CC-BY-4.0",
        "priority": 2,
        "max_age_hours": 336,
        "enabled": True,
    },
    "trenitalia": {
        "name": "Trenitalia (reseau national - dati Toscana)",
        "type": "gtfs",
        "url": "https://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/4f85393b-357d-443d-8378-65de4198505f/download/trenitalia.gtfs",
        "country": "IT",
        "licence": "CC-BY-4.0",
        "priority": 2,
        "max_age_hours": 336,
        "enabled": True,
    },
    "cff_sbb": {
        "name": "CFF/SBB Suisse",
        "type": "gtfs",
        "url": "https://data.opentransportdata.swiss/dataset/timetable-2026-gtfs2020/permalink",
        "country": "CH",
        "licence": "Open Data",
        "priority": 2,
        "max_age_hours": 336,
        "enabled": True,
    },
    "obb": {
        "name": "ÖBB Autriche",
        "type": "gtfs",
        "url": "https://static.oebb.at/open-data/soll-fahrplan-gtfs/GTFS_Fahrplan_2026.zip",
        "country": "AT",
        "licence": "Open Data",
        "priority": 1,
        "max_age_hours": 168,
        "enabled": True,
    },
    "sncb": {
        "name": "SNCB Belgique",
        "type": "gtfs",
        "url": "https://gtfs.irail.be/nmbs/gtfs/latest.zip",
        "country": "BE",
        "licence": "CC-BY-4.0",
        "priority": 2,
        "max_age_hours": 336,
        "enabled": True,
    },
}

# Liste des pays européens pour filtrage
EUROPEAN_COUNTRIES = [
    "FR",
    "DE",
    "IT",
    "ES",
    "CH",
    "AT",
    "BE",
    "NL",
    "UK",
    "SE",
    "NO",
    "DK",
    "FI",
    "IE",
    "PT",
    "PL",
    "CZ",
    "HU",
    "RO",
    "BG",
    "HR",
    "SI",
    "SK",
    "LT",
    "LV",
    "EE",
    "LU",
]
